In [30]:
%load_ext autoreload
%autoreload 2

# Importing necessary libraries and the functions from the provided file
import pandas as pd
from pandas import DataFrame
from shuffle_sample import column_shuffle_df, row_shuffle_df, sample_df, get_permutations

# Create DataFrame
data = {
    'int': [1, 2, 3, 4, 5],
    'str': ['apple', 'pear', 'grape', 'kiwi', 'lime'],
    'duplicates': ['dog', 'cat', 'bird', 'cat', 'dog']
}

df = pd.DataFrame(data)

df


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


int    str duplicates
0    1  apple        dog
1    2   pear        cat
2    3  grape       bird
3    4   kiwi        cat
4    5   lime        dog

In [31]:
column_shuffle_tables, perms  = column_shuffle_df(df, 10)
# The first table will be the original table
column_shuffle_tables[0]

int    str duplicates
0    1  apple        dog
1    2   pear        cat
2    3  grape       bird
3    4   kiwi        cat
4    5   lime        dog

In [32]:
column_shuffle_tables[1]

str duplicates  int
0  apple        dog    1
1   pear        cat    2
2  grape       bird    3
3   kiwi        cat    4
4   lime        dog    5

In [33]:
row_shuffle_tables = row_shuffle_df(df, 10)
row_shuffle_tables[1]

int    str duplicates
2    3  grape       bird
3    4   kiwi        cat
1    2   pear        cat
0    1  apple        dog
4    5   lime        dog

In [34]:
sample_tables = sample_df(df, 10 , 0.5)
sample_tables[1]

int    str duplicates
0    1  apple        dog
2    3  grape       bird

In [35]:
sample_tables[0]

int    str duplicates
0    1  apple        dog
1    2   pear        cat
2    3  grape       bird
3    4   kiwi        cat
4    5   lime        dog

In [36]:
from single_table_processing import get_most_similar_rows
text_to_compare = "My dog loves to eat pear"
similar_rows = get_most_similar_rows(df, text_to_compare, k = 3)
similar_rows

int    str duplicates
0    1  apple        dog
1    2   pear        cat
4    5   lime        dog

In [37]:

from single_table_processing import get_most_similar_rows


text_to_compare = "My dog loves to eat pear"
similar_rows = get_most_similar_rows(df, text_to_compare)
print(similar_rows)


   int    str duplicates
0    1  apple        dog
1    2   pear        cat
4    5   lime        dog
2    3  grape       bird
3    4   kiwi        cat


In [38]:
similar_rows = get_most_similar_rows(df, text_to_compare, k = 3)
similar_rows

int    str duplicates
0    1  apple        dog
1    2   pear        cat
4    5   lime        dog

In [39]:
from single_table_processing import get_most_similar_cols
text_to_compare = "My cat loves to eat pear"
similar_cols = get_most_similar_cols(df, text_to_compare)
similar_cols

duplicates    str  int
0        dog  apple    1
1        cat   pear    2
2       bird  grape    3
3        cat   kiwi    4
4        dog   lime    5

In [40]:
df 

int    str duplicates
0    1  apple        dog
1    2   pear        cat
2    3  grape       bird
3    4   kiwi        cat
4    5   lime        dog

In [41]:
from single_table_processing import rank_rows_by_tfidf

rank_rows_by_tfidf(df)

int    str duplicates
2    3  grape       bird
0    1  apple        dog
1    2   pear        cat
3    4   kiwi        cat
4    5   lime        dog

In [42]:
from huggingface_dataset import *

In [43]:

# Generating a table where the cell value is the multiplication of the column number and the row number
long_table_multiplied = {
    f"Column_{i}": [i * j for j in range(100)] for i in range(10)
}

# Converting the table to a DataFrame for display
df_long_table_multiplied = DataFrame(long_table_multiplied)
df_long_table_multiplied.head(10)  # Displaying the first 10 rows of the table for reference


Column_0  Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  \
0         0         0         0         0         0         0         0   
1         0         1         2         3         4         5         6   
2         0         2         4         6         8        10        12   
3         0         3         6         9        12        15        18   
4         0         4         8        12        16        20        24   
5         0         5        10        15        20        25        30   
6         0         6        12        18        24        30        36   
7         0         7        14        21        28        35        42   
8         0         8        16        24        32        40        48   
9         0         9        18        27        36        45        54   

   Column_7  Column_8  Column_9  
0         0         0         0  
1         7         8         9  
2        14        16        18  
3        21        24        27  
4        28        32        36  
5        35        40        45  
6        42        48        54  
7        49        56        63  
8        56        64        72  
9        63        72        81

In [44]:
def number_to_words(num):
    """Convert a number into words."""
    if num == 0:
        return 'zero'

    under_20 = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
                'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen']

    tens = ['', '', 'twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety']

    if num < 20:
        return under_20[num - 1]

    if num < 100:
        return tens[num // 10] + ('' if num % 10 == 0 else ' ' + under_20[num % 10 - 1])

    if num < 1000:
        return under_20[num // 100 - 1] + ' hundred' + ('' if num % 100 == 0 else ' ' + number_to_words(num % 100))

    if num < 1000000:
        return number_to_words(num // 1000) + ' thousand' + ('' if num % 1000 == 0 else ' ' + number_to_words(num % 1000))

    return str(num)  # This function handles up to 999,999; other numbers will be returned as-is

# Convert the cell values in the DataFrame to English words
for col in df_long_table_multiplied.columns:
    df_long_table_multiplied[col] = df_long_table_multiplied[col].apply(lambda x: number_to_words(int(x)))

df_long_table_multiplied.head(10)


Column_0 Column_1  Column_2      Column_3      Column_4     Column_5  \
0     zero     zero      zero          zero          zero         zero   
1     zero      one       two         three          four         five   
2     zero      two      four           six         eight          ten   
3     zero    three       six          nine        twelve      fifteen   
4     zero     four     eight        twelve       sixteen       twenty   
5     zero     five       ten       fifteen        twenty  twenty five   
6     zero      six    twelve      eighteen   twenty four       thirty   
7     zero    seven  fourteen    twenty one  twenty eight  thirty five   
8     zero    eight   sixteen   twenty four    thirty two        forty   
9     zero     nine  eighteen  twenty seven    thirty six   forty five   

      Column_6      Column_7     Column_8      Column_9  
0         zero          zero         zero          zero  
1          six         seven        eight          nine  
2       twelve      fourteen      sixteen      eighteen  
3     eighteen    twenty one  twenty four  twenty seven  
4  twenty four  twenty eight   thirty two    thirty six  
5       thirty   thirty five        forty    forty five  
6   thirty six     forty two  forty eight    fifty four  
7    forty two    forty nine    fifty six   sixty three  
8  forty eight     fifty six   sixty four   seventy two  
9   fifty four   sixty three  seventy two    eighty one

In [52]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [53]:
example_tables = chunk_tables([df_long_table_multiplied, df_long_table_multiplied], 'bert-base-uncased', 512, tokenizer, max_col=3, max_row=10, max_token_per_cell=1)

In [59]:
example_tables = chunk_neighbor_tables([df_long_table_multiplied, df_long_table_multiplied],  'Column_4',2, 'bert-base-uncased', 512, tokenizer)

In [60]:
# for table in example_tables:
#     print(table)

{'table':         Column_2      Column_3      Column_4             Column_5  \
0           zero          zero          zero                 zero   
1            two         three          four                 five   
2           four           six         eight                  ten   
3            six          nine        twelve              fifteen   
4          eight        twelve       sixteen               twenty   
5            ten       fifteen        twenty          twenty five   
6         twelve      eighteen   twenty four               thirty   
7       fourteen    twenty one  twenty eight          thirty five   
8        sixteen   twenty four    thirty two                forty   
9       eighteen  twenty seven    thirty six           forty five   
10        twenty        thirty         forty                fifty   
11    twenty two  thirty three    forty four           fifty five   
12   twenty four    thirty six   forty eight                sixty   
13    twenty six   thirt

In [77]:
example_tables = chunk_neighbor_tables([df_long_table_multiplied, df_long_table_multiplied],  'Column_4',2, 'bert-base-uncased', 512, tokenizer)

In [78]:
model_name = 'bert-base-uncased'
dataset = TableColumnDataset(example_tables, tokenizer, 512, "[PAD]", model_name)


In [79]:
from torch.utils.data import DataLoader
dataloader = DataLoader(dataset, batch_size=32, shuffle=False)


In [80]:
for batch in dataloader:
    if model_name.startswith("google/tapas"):
        inputs, positions, indices = batch
        print(inputs)
        print(positions)
        print(indices)
        # Further processing for TAPAS model...
    else:
        input_ids, attention_mask, token_positions, positions, indices = batch
        print(input_ids)
        print(attention_mask)
        print(token_positions)
        print(positions)
        print(indices)

tensor([[ 101, 5930, 1035,  ...,    0,    0,    0],
        [ 101, 5930, 1035,  ...,    0,    0,    0],
        [ 101, 5930, 1035,  ...,    0,    0,    0],
        ...,
        [ 101, 5930, 1035,  ...,    0,    0,    0],
        [ 101, 5930, 1035,  ...,    0,    0,    0],
        [ 101, 5930, 1035,  ...,    0,    0,    0]])
tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])
[tensor([0, 0, 0, 0, 0, 0, 0, 0]), tensor([41, 49, 90, 99, 41, 49, 90, 99]), tensor([ 86, 127, 185, 201,  86, 127, 185, 201]), tensor([131, 221, 279, 295, 131, 221, 279, 295]), tensor([177, 310, 367, 384, 177, 310, 367, 384])]
[[tensor([2, 2, 2, 2, 2, 2, 2, 2]), tensor([7, 7, 7, 7, 7, 7, 7, 7])], [tensor([ 0, 25, 50, 75,  0, 25, 50, 75]), tensor([ 25,  50,  75, 100,  25,  50,  75, 100])]]
tensor([0, 0, 0, 0, 1, 1, 1, 1])


In [8]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import pandas as pd

tokenizer = AutoTokenizer.from_pretrained("microsoft/tapex-large-finetuned-wtq")
model = AutoModelForSeq2SeqLM.from_pretrained("microsoft/tapex-large-finetuned-wtq")

# prepare table + question
data = {"Actors": ["Brad Pitt", "Leonardo Di Caprio", "George Clooney"], "Number of movies": ["87", "53", "69"]}
table = pd.DataFrame.from_dict(data)
question = "abc"

encoding = tokenizer(table, question, return_tensors="pt")

# let the model generate an answer autoregressively
outputs = model.generate(**encoding)

# decode back to text
predicted_answer = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]
print(predicted_answer)

c:\Users\Ben\anaconda3\envs\545\lib\site-packages\transformers\generation\utils.py:1288: UserWarning: Neither `max_length` nor `max_new_tokens` has been set, `max_length` will default to 1024 (`generation_config.max_length`). Controlling `max_length` via the config is deprecated and `max_length` will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


 kalimba edwards


In [43]:
tokenizer = AutoTokenizer.from_pretrained("microsoft/tapex-large-finetuned-tabfact")
col_tokens = tokenizer.tokenize("Brad Pitt")
input_ids = tokenizer.convert_tokens_to_ids(col_tokens)
print(col_tokens)
print(input_ids)

['br', 'ad', 'Ġp', 'itt']
[3809, 625, 181, 2582]


In [42]:
data = {"Actors": ["Brad Pitt", "Leonardo Di Caprio", "George Clooney"], "Number of movies": ["87", "53", "69"]}
table = pd.DataFrame.from_dict(data)
encoding = tokenizer(table, "", return_tensors="pt")
print(encoding)

You provide nothing to query with respect to the table.


{'input_ids': tensor([[    0,  9119,  4832,  5552,  1721,   346,     9,  4133,  3236,   112,
          4832,  5378,   625,   181,  2582,  1721,  8176,  3236,   132,  4832,
          2084,   261,  6782,  2269,  2927, 12834,  1721,  4268,  3236,   155,
          4832,  5473, 26875, 42771,  6071,  1721,  5913,     2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [36]:
data = {"Actors": ["Brad Pitt", "Leonardo Di Caprio", "George Clooney"]}
table = pd.DataFrame.from_dict(data)
encoding = tokenizer(table, "", return_tensors="pt")
print(encoding['input_ids'])

You provide nothing to query with respect to the table.


tensor([[    0,  9119,  4832,  5552,  3236,   112,  4832,  5378,   625,   181,
          2582,  3236,   132,  4832,  2084,   261,  6782,  2269,  2927, 12834,
          3236,   155,  4832,  5473, 26875, 42771,  6071,     2]])


In [32]:
data = {"Actors": ["Brad Pitt"]}
table = pd.DataFrame.from_dict(data)
encoding = tokenizer(table, "", return_tensors="pt")
print(encoding['input_ids'])

You provide nothing to query with respect to the table.


tensor([[    0, 11311,  4832,  5552,  3236,   112,  4832,  5378,   625,   181,
          2582,     2]])


In [31]:
data = {"Actors": [""]}
table = pd.DataFrame.from_dict(data)
encoding = tokenizer(table, "", return_tensors="pt")
print(encoding['input_ids'])

You provide nothing to query with respect to the table.


tensor([[    0, 11311,  4832,  5552,  3236,   112,  4832,     2]])


In [33]:
data = {"": [""]}
table = pd.DataFrame.from_dict(data)
encoding = tokenizer(table, "", return_tensors="pt")
print(encoding['input_ids'])

You provide nothing to query with respect to the table.


tensor([[    0, 11311,  4832,  1437,  3236,   112,  4832,     2]])


In [14]:
import torch

def get_s_token_embedding(model, tokenizer, table, question):
    # Tokenize the table and question
    encoding = tokenizer(table, question, return_tensors="pt")

    # Extract input IDs from the encoding
    input_ids = encoding['input_ids']

    # Pass the input IDs through the embed_tokens layer
    embeddings_output = model.model.encoder.embed_tokens(input_ids)
    print(embeddings_output.shape)

    # Get the token ID for <s>
    token_id = tokenizer.convert_tokens_to_ids('<s>')

    # Fetch the embeddings for <s> token from the output
    s_token_embedding = embeddings_output[0][input_ids[0] == token_id]

    return s_token_embedding

# Example usage:
embedding = get_s_token_embedding(model, tokenizer, table, question)
print(embedding.shape)


torch.Size([1, 40, 1024])
torch.Size([1, 1024])


In [12]:
def get_decoder_last_hidden_state(model, tokenizer, table, question):
    # Tokenize the table and question
    encoding = tokenizer(table, question, return_tensors="pt")

    # Use the forward method of the model to get the outputs
    outputs = model(**encoding)

    # The first output is typically the last hidden state of the decoder
    decoder_last_hidden_state = outputs[0]

    return decoder_last_hidden_state

# Example usage:
decoder_hidden_state = get_decoder_last_hidden_state(model, tokenizer, table, question)
print(decoder_hidden_state.shape)

torch.Size([1, 40, 50265])


In [19]:
def get_lm_head_inputs(model, tokenizer, table, question):
    # Tokenize the table and question
    encoding = tokenizer(table, question, return_tensors="pt")

    # Use the forward method of the model to get the outputs
    outputs = model(**encoding)

    # The first output is typically the last hidden state of the decoder
    decoder_last_hidden_state = outputs[0]

    return decoder_last_hidden_state

# Example usage:
lm_head_input = get_lm_head_inputs(model, tokenizer, table, question)
print(lm_head_input.shape)


torch.Size([1, 40, 50265])


In [22]:
def get_decoder_output_before_lm_head(model, tokenizer, table, question):
    # Tokenize the table and question
    encoding = tokenizer(table, question, return_tensors="pt")
    input_ids = encoding['input_ids']
    attention_mask = encoding.get('attention_mask', None)

    # Directly use the model's BART structure to get the encoder's output
    encoder_outputs = model.model.encoder(input_ids, attention_mask=attention_mask)
    
    # Retrieve decoder's output using encoder's outputs and attention mask
    decoder_outputs = model.model.decoder(
        input_ids=input_ids, 
        encoder_hidden_states=encoder_outputs[0], 
        attention_mask=attention_mask
    )

    # The first output of the decoder contains the last hidden states
    return decoder_outputs[0]

# Example usage:
decoder_output = get_decoder_output_before_lm_head(model, tokenizer, table, question)
print(decoder_output.shape)


torch.Size([1, 40, 1024])


In [24]:
print(encoding)

{'input_ids': tensor([[    0,  4091,   438, 11311,  4832,  5552,  1721,   346,     9,  4133,
          3236,   112,  4832,  5378,   625,   181,  2582,  1721,  8176,  3236,
           132,  4832,  2084,   261,  6782,  2269,  2927, 12834,  1721,  4268,
          3236,   155,  4832,  5473, 26875, 42771,  6071,  1721,  5913,     2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
