In [1]:
%load_ext autoreload
%autoreload 2

# Importing necessary libraries and the functions from the provided file
import pandas as pd
from pandas import DataFrame
from shuffle_sample import column_shuffle_df, row_shuffle_df, sample_df, get_permutations

# Create DataFrame
data = {
    'int': [1, 2, 3, 4, 5],
    'str': ['apple', 'pear', 'grape', 'kiwi', 'lime'],
    'duplicates': ['dog', 'cat', 'bird', 'cat', 'dog']
}

df = pd.DataFrame(data)

df


int    str duplicates
0    1  apple        dog
1    2   pear        cat
2    3  grape       bird
3    4   kiwi        cat
4    5   lime        dog

In [2]:
column_shuffle_tables, perms  = column_shuffle_df(df, 10)
# The first table will be the original table
column_shuffle_tables[0]

int    str duplicates
0    1  apple        dog
1    2   pear        cat
2    3  grape       bird
3    4   kiwi        cat
4    5   lime        dog

In [3]:
column_shuffle_tables[1]

int duplicates    str
0    1        dog  apple
1    2        cat   pear
2    3       bird  grape
3    4        cat   kiwi
4    5        dog   lime

In [4]:
row_shuffle_tables = row_shuffle_df(df, 10)
row_shuffle_tables[1]

int    str duplicates
4    5   lime        dog
2    3  grape       bird
0    1  apple        dog
1    2   pear        cat
3    4   kiwi        cat

In [5]:
sample_tables = sample_df(df, 10 , 0.5)
sample_tables[1]

int   str duplicates
1    2  pear        cat
4    5  lime        dog

In [6]:
sample_tables[0]

int    str duplicates
0    1  apple        dog
1    2   pear        cat
2    3  grape       bird
3    4   kiwi        cat
4    5   lime        dog

In [7]:
from single_table_processing import get_most_similar_rows
text_to_compare = "My dog loves to eat pear"
similar_rows = get_most_similar_rows(df, text_to_compare, k = 3)
similar_rows

int    str duplicates
0    1  apple        dog
1    2   pear        cat
4    5   lime        dog

In [8]:

from single_table_processing import get_most_similar_rows


text_to_compare = "My dog loves to eat pear"
similar_rows = get_most_similar_rows(df, text_to_compare)
print(similar_rows)


   int    str duplicates
0    1  apple        dog
1    2   pear        cat
4    5   lime        dog
2    3  grape       bird
3    4   kiwi        cat


In [9]:
similar_rows = get_most_similar_rows(df, text_to_compare, k = 3)
similar_rows

int    str duplicates
0    1  apple        dog
1    2   pear        cat
4    5   lime        dog

In [10]:
from single_table_processing import get_most_similar_cols
text_to_compare = "My cat loves to eat pear"
similar_cols = get_most_similar_cols(df, text_to_compare)
similar_cols

duplicates    str  int
0        dog  apple    1
1        cat   pear    2
2       bird  grape    3
3        cat   kiwi    4
4        dog   lime    5

In [11]:
df 

int    str duplicates
0    1  apple        dog
1    2   pear        cat
2    3  grape       bird
3    4   kiwi        cat
4    5   lime        dog

In [12]:
from single_table_processing import rank_rows_by_tfidf

rank_rows_by_tfidf(df)

int    str duplicates
2    3  grape       bird
0    1  apple        dog
1    2   pear        cat
3    4   kiwi        cat
4    5   lime        dog

In [13]:
from huggingface_dataset import *

In [14]:

# Generating a table where the cell value is the multiplication of the column number and the row number
long_table_multiplied = {
    f"Column_{i}": [i * j for j in range(100)] for i in range(10)
}

# Converting the table to a DataFrame for display
df_long_table_multiplied = DataFrame(long_table_multiplied)
df_long_table_multiplied.head(10)  # Displaying the first 10 rows of the table for reference


Column_0  Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  \
0         0         0         0         0         0         0         0   
1         0         1         2         3         4         5         6   
2         0         2         4         6         8        10        12   
3         0         3         6         9        12        15        18   
4         0         4         8        12        16        20        24   
5         0         5        10        15        20        25        30   
6         0         6        12        18        24        30        36   
7         0         7        14        21        28        35        42   
8         0         8        16        24        32        40        48   
9         0         9        18        27        36        45        54   

   Column_7  Column_8  Column_9  
0         0         0         0  
1         7         8         9  
2        14        16        18  
3        21        24        27  
4        28        32        36  
5        35        40        45  
6        42        48        54  
7        49        56        63  
8        56        64        72  
9        63        72        81

In [15]:
def number_to_words(num):
    """Convert a number into words."""
    if num == 0:
        return 'zero'

    under_20 = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
                'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen']

    tens = ['', '', 'twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety']

    if num < 20:
        return under_20[num - 1]

    if num < 100:
        return tens[num // 10] + ('' if num % 10 == 0 else ' ' + under_20[num % 10 - 1])

    if num < 1000:
        return under_20[num // 100 - 1] + ' hundred' + ('' if num % 100 == 0 else ' ' + number_to_words(num % 100))

    if num < 1000000:
        return number_to_words(num // 1000) + ' thousand' + ('' if num % 1000 == 0 else ' ' + number_to_words(num % 1000))

    return str(num)  # This function handles up to 999,999; other numbers will be returned as-is

# Convert the cell values in the DataFrame to English words
for col in df_long_table_multiplied.columns:
    df_long_table_multiplied[col] = df_long_table_multiplied[col].apply(lambda x: number_to_words(int(x)))

df_long_table_multiplied.head(10)


Column_0 Column_1  Column_2      Column_3      Column_4     Column_5  \
0     zero     zero      zero          zero          zero         zero   
1     zero      one       two         three          four         five   
2     zero      two      four           six         eight          ten   
3     zero    three       six          nine        twelve      fifteen   
4     zero     four     eight        twelve       sixteen       twenty   
5     zero     five       ten       fifteen        twenty  twenty five   
6     zero      six    twelve      eighteen   twenty four       thirty   
7     zero    seven  fourteen    twenty one  twenty eight  thirty five   
8     zero    eight   sixteen   twenty four    thirty two        forty   
9     zero     nine  eighteen  twenty seven    thirty six   forty five   

      Column_6      Column_7     Column_8      Column_9  
0         zero          zero         zero          zero  
1          six         seven        eight          nine  
2       twelve      fourteen      sixteen      eighteen  
3     eighteen    twenty one  twenty four  twenty seven  
4  twenty four  twenty eight   thirty two    thirty six  
5       thirty   thirty five        forty    forty five  
6   thirty six     forty two  forty eight    fifty four  
7    forty two    forty nine    fifty six   sixty three  
8  forty eight     fifty six   sixty four   seventy two  
9   fifty four   sixty three  seventy two    eighty one

In [16]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [17]:
example_tables = chunk_tables([df_long_table_multiplied, df_long_table_multiplied], 'bert-base-uncased', 512, tokenizer, max_col=3, max_row=10, max_token_per_cell=1)

In [18]:
example_tables = chunk_neighbor_tables([df_long_table_multiplied, df_long_table_multiplied],  'Column_4',2, 'bert-base-uncased', 512, tokenizer)

In [19]:
# for table in example_tables:
#     print(table)

In [20]:
example_tables = chunk_neighbor_tables([df_long_table_multiplied, df_long_table_multiplied],  'Column_4',2, 'bert-base-uncased', 512, tokenizer)

In [21]:
model_name = 'bert-base-uncased'
dataset = TableColumnDataset(example_tables, tokenizer, 512, "[PAD]", model_name)


In [22]:
from torch.utils.data import DataLoader
dataloader = DataLoader(dataset, batch_size=32, shuffle=False)


In [23]:
for batch in dataloader:
    if model_name.startswith("google/tapas"):
        inputs, positions, indices = batch
        print(inputs)
        print(positions)
        print(indices)
        # Further processing for TAPAS model...
    else:
        input_ids, attention_mask, token_positions, positions, indices = batch
        print(input_ids)
        print(attention_mask)
        print(token_positions)
        print(positions)
        print(indices)

tensor([[ 101, 5930, 1035,  ...,    0,    0,    0],
        [ 101, 5930, 1035,  ...,    0,    0,    0],
        [ 101, 5930, 1035,  ...,    0,    0,    0],
        ...,
        [ 101, 5930, 1035,  ...,    0,    0,    0],
        [ 101, 5930, 1035,  ...,    0,    0,    0],
        [ 101, 5930, 1035,  ...,    0,    0,    0]])
tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])
[tensor([0, 0, 0, 0, 0, 0, 0, 0]), tensor([41, 49, 90, 99, 41, 49, 90, 99]), tensor([ 86, 127, 185, 201,  86, 127, 185, 201]), tensor([131, 221, 279, 295, 131, 221, 279, 295]), tensor([177, 310, 367, 384, 177, 310, 367, 384])]
[[tensor([2, 2, 2, 2, 2, 2, 2, 2]), tensor([7, 7, 7, 7, 7, 7, 7, 7])], [tensor([ 0, 25, 50, 75,  0, 25, 50, 75]), tensor([ 25,  50,  75, 100,  25,  50,  75, 100])]]
tensor([0, 0, 0, 0, 1, 1, 1, 1])


In [51]:
from transformers import AutoTokenizer, TapasModel
import pandas as pd

tokenizer = AutoTokenizer.from_pretrained("google/tapas-base")
model = TapasModel.from_pretrained("google/tapas-base")

data = {
    "Actors": ["Brad Pitt", "Leonardo Di Caprio", "George Clooney"],
    "Age": ["56", "45", "59"],
    "Number of movies": ["87", "53", "69"],
}
table = pd.DataFrame.from_dict(data)
queries = [""]

inputs = tokenizer(table=table, queries=[""],  padding="max_length", return_tensors="pt")


In [52]:
batch_input_ids = []
batch_token_type_ids = []
batch_attention_masks = []

In [53]:
batch_input_ids.append(inputs["input_ids"][0])
batch_token_type_ids.append(inputs["token_type_ids"][0])
batch_attention_masks.append(inputs["attention_mask"][0])
batch_input_ids.append(inputs["input_ids"][0])
batch_token_type_ids.append(inputs["token_type_ids"][0])
batch_attention_masks.append(inputs["attention_mask"][0])

In [54]:
print(inputs.keys())
print(inputs["input_ids"].shape)
print(inputs["token_type_ids"].shape)
print(inputs["attention_mask"].shape)

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])
torch.Size([1, 512])
torch.Size([1, 512, 7])
torch.Size([1, 512])


In [55]:
batched_inputs = {
    "input_ids": torch.stack(batch_input_ids, dim=0),
    "token_type_ids": torch.stack(batch_token_type_ids, dim=0),
    "attention_mask": torch.stack(batch_attention_masks, dim=0)
}

print(batched_inputs.keys())
print(batched_inputs["input_ids"].shape)
print(batched_inputs["token_type_ids"].shape)
print(batched_inputs["attention_mask"].shape)


dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])
torch.Size([2, 512])
torch.Size([2, 512, 7])
torch.Size([2, 512])


In [65]:
for row_id in range(1, max(batched_inputs["token_type_ids"][1][:, 2]) + 1):
    indices = torch.where(batched_inputs["token_type_ids"][1][:, 2] == row_id)[0]
    print(indices)

tensor([ 7,  8,  9, 10])
tensor([11, 12, 13, 14, 15, 16])
tensor([17, 18, 19, 20, 21, 22])


In [67]:
outputs = model(**batched_inputs)

In [69]:
print(outputs.last_hidden_state.shape)
embeddings = outputs.last_hidden_state[0][indices]

torch.Size([2, 512, 768])


In [71]:
embeddings.shape

torch.Size([6, 768])

In [73]:
row_embedding = embeddings.mean(dim=0)
row_embedding.shape

torch.Size([768])

In [6]:
from transformers import BertTokenizer, BertModel
import torch
model_name = "bert-base-uncased"
model = BertModel.from_pretrained(model_name)
tokenizer = BertTokenizer.from_pretrained(model_name)

c:\Users\Ben\anaconda3\envs\545\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Ben\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.pre

In [7]:
sequences = ["This is a positive sentence!", "This is a negative comment."]
inputs = tokenizer(sequences, return_tensors="pt", padding=True, truncation=True, max_length=128)


In [10]:
print(inputs.keys())

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])


In [11]:
print(inputs['input_ids'])
print(inputs['token_type_ids'])
print(inputs['attention_mask'])

tensor([[ 101, 2023, 2003, 1037, 3893, 6251,  999,  102],
        [ 101, 2023, 2003, 1037, 4997, 7615, 1012,  102]])
tensor([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]])


In [14]:
input_ids = inputs["input_ids"]
attention_masks = inputs["attention_mask"]

# Model inference
with torch.no_grad():
    outputs = model(input_ids=input_ids, attention_mask=attention_masks)
outputs[0]

tensor([[[ 0.0385,  0.0743,  0.0242,  ..., -0.0842,  0.0863,  0.4935],
         [-0.6866, -0.3217, -0.0882,  ..., -0.4354,  0.4125,  0.3192],
         [-0.3456, -0.1643,  0.4086,  ..., -0.1561, -0.1173,  0.8148],
         ...,
         [ 0.4874, -0.1094,  0.0120,  ..., -0.1576, -0.2751, -0.1945],
         [-0.1658, -0.0188, -0.0298,  ...,  0.6038,  0.0696, -0.1061],
         [ 0.6924, -0.0049, -0.3164,  ...,  0.2431, -0.8448, -0.1762]],

        [[ 0.0132,  0.3487, -0.4119,  ..., -0.1506,  0.4289,  0.5168],
         [-0.2394, -0.1223, -0.4221,  ..., -0.4399,  0.9538,  0.6297],
         [ 0.1617, -0.4871,  0.0902,  ..., -0.2221,  0.3014,  1.2299],
         ...,
         [ 0.4137, -0.0839, -0.1032,  ..., -0.1113, -0.1187,  0.0429],
         [ 0.5053,  0.2275, -0.6482,  ...,  0.1001, -0.3152, -0.4392],
         [-0.1526,  0.1795, -0.2566,  ...,  0.0928,  0.4112,  0.2930]]])

In [15]:
from transformers import     RobertaTokenizer, RobertaModel
import torch

# Load pre-trained model and tokenizer
model_name = "roberta-base"
model = RobertaModel.from_pretrained(model_name)
tokenizer = RobertaTokenizer.from_pretrained(model_name)

# Sample input sequences
sequences = ["This is a positive sentence!", "This is a negative comment."]

# Tokenize and pad sequences
inputs = tokenizer(sequences, return_tensors="pt", padding=True, truncation=True, max_length=128)

input_ids = inputs["input_ids"]
attention_masks = inputs["attention_mask"]

# Model inference
with torch.no_grad():
    outputs = model(input_ids=input_ids, attention_mask=attention_masks)
outputs[0]


Some weights of the model checkpoint at roberta-base were not used when initializing RobertaModel: ['lm_head.dense.weight', 'lm_head.layer_norm.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.bias', 'lm_head.bias', 'lm_head.decoder.weight']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tensor([[[-0.0522,  0.0834, -0.0091,  ..., -0.0503, -0.0382, -0.0073],
         [ 0.1267,  0.1119,  0.0542,  ...,  0.4205,  0.0425,  0.0248],
         [ 0.1743,  0.1795,  0.1761,  ..., -0.0614,  0.0221,  0.1734],
         ...,
         [ 0.0474,  0.0388, -0.0181,  ..., -0.0735,  0.0274,  0.0399],
         [ 0.0750, -0.0334,  0.0773,  ..., -0.0514, -0.1612,  0.1572],
         [-0.0476,  0.0874, -0.0376,  ..., -0.0874, -0.0322, -0.0266]],

        [[-0.0680,  0.1042, -0.0158,  ..., -0.0747, -0.0407, -0.0827],
         [ 0.0012,  0.2099,  0.0328,  ...,  0.3939, -0.0008,  0.0491],
         [ 0.0610,  0.2271,  0.1642,  ..., -0.0786,  0.0827,  0.1270],
         ...,
         [-0.0270, -0.0110, -0.0062,  ...,  0.2534,  0.0237,  0.0165],
         [-0.0522,  0.0988, -0.0407,  ..., -0.0977, -0.0449, -0.1178],
         [ 0.0322,  0.0708,  0.0252,  ...,  0.1127,  0.0085,  0.0161]]])