In [1]:
%load_ext autoreload
%autoreload 2

# Importing necessary libraries and the functions from the provided file
import pandas as pd
from pandas import DataFrame
from shuffle_sample import column_shuffle_df, row_shuffle_df, sample_df, get_permutations

# Create DataFrame
data = {
    'int': [1, 2, 3, 4, 5],
    'str': ['apple', 'pear', 'grape', 'kiwi', 'lime'],
    'duplicates': ['dog', 'cat', 'bird', 'cat', 'dog']
}

df = pd.DataFrame(data)

df


int    str duplicates
0    1  apple        dog
1    2   pear        cat
2    3  grape       bird
3    4   kiwi        cat
4    5   lime        dog

In [2]:
column_shuffle_tables, perms  = column_shuffle_df(df, 10)
# The first table will be the original table
column_shuffle_tables[0]

int    str duplicates
0    1  apple        dog
1    2   pear        cat
2    3  grape       bird
3    4   kiwi        cat
4    5   lime        dog

In [3]:
column_shuffle_tables[1]

int duplicates    str
0    1        dog  apple
1    2        cat   pear
2    3       bird  grape
3    4        cat   kiwi
4    5        dog   lime

In [4]:
row_shuffle_tables = row_shuffle_df(df, 10)
row_shuffle_tables[1]

int    str duplicates
4    5   lime        dog
2    3  grape       bird
0    1  apple        dog
1    2   pear        cat
3    4   kiwi        cat

In [5]:
sample_tables = sample_df(df, 10 , 0.5)
sample_tables[1]

int   str duplicates
1    2  pear        cat
4    5  lime        dog

In [6]:
sample_tables[0]

int    str duplicates
0    1  apple        dog
1    2   pear        cat
2    3  grape       bird
3    4   kiwi        cat
4    5   lime        dog

In [7]:
from single_table_processing import get_most_similar_rows
text_to_compare = "My dog loves to eat pear"
similar_rows = get_most_similar_rows(df, text_to_compare, k = 3)
similar_rows

int    str duplicates
0    1  apple        dog
1    2   pear        cat
4    5   lime        dog

In [8]:

from single_table_processing import get_most_similar_rows


text_to_compare = "My dog loves to eat pear"
similar_rows = get_most_similar_rows(df, text_to_compare)
print(similar_rows)


   int    str duplicates
0    1  apple        dog
1    2   pear        cat
4    5   lime        dog
2    3  grape       bird
3    4   kiwi        cat


In [9]:
similar_rows = get_most_similar_rows(df, text_to_compare, k = 3)
similar_rows

int    str duplicates
0    1  apple        dog
1    2   pear        cat
4    5   lime        dog

In [10]:
from single_table_processing import get_most_similar_cols
text_to_compare = "My cat loves to eat pear"
similar_cols = get_most_similar_cols(df, text_to_compare)
similar_cols

duplicates    str  int
0        dog  apple    1
1        cat   pear    2
2       bird  grape    3
3        cat   kiwi    4
4        dog   lime    5

In [11]:
df 

int    str duplicates
0    1  apple        dog
1    2   pear        cat
2    3  grape       bird
3    4   kiwi        cat
4    5   lime        dog

In [12]:
from single_table_processing import rank_rows_by_tfidf

rank_rows_by_tfidf(df)

int    str duplicates
2    3  grape       bird
0    1  apple        dog
1    2   pear        cat
3    4   kiwi        cat
4    5   lime        dog

In [13]:
from huggingface_dataset import *

In [14]:

# Generating a table where the cell value is the multiplication of the column number and the row number
long_table_multiplied = {
    f"Column_{i}": [i * j for j in range(100)] for i in range(10)
}

# Converting the table to a DataFrame for display
df_long_table_multiplied = DataFrame(long_table_multiplied)
df_long_table_multiplied.head(10)  # Displaying the first 10 rows of the table for reference


Column_0  Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  \
0         0         0         0         0         0         0         0   
1         0         1         2         3         4         5         6   
2         0         2         4         6         8        10        12   
3         0         3         6         9        12        15        18   
4         0         4         8        12        16        20        24   
5         0         5        10        15        20        25        30   
6         0         6        12        18        24        30        36   
7         0         7        14        21        28        35        42   
8         0         8        16        24        32        40        48   
9         0         9        18        27        36        45        54   

   Column_7  Column_8  Column_9  
0         0         0         0  
1         7         8         9  
2        14        16        18  
3        21        24        27  
4        28        32        36  
5        35        40        45  
6        42        48        54  
7        49        56        63  
8        56        64        72  
9        63        72        81

In [15]:
def number_to_words(num):
    """Convert a number into words."""
    if num == 0:
        return 'zero'

    under_20 = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
                'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen']

    tens = ['', '', 'twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety']

    if num < 20:
        return under_20[num - 1]

    if num < 100:
        return tens[num // 10] + ('' if num % 10 == 0 else ' ' + under_20[num % 10 - 1])

    if num < 1000:
        return under_20[num // 100 - 1] + ' hundred' + ('' if num % 100 == 0 else ' ' + number_to_words(num % 100))

    if num < 1000000:
        return number_to_words(num // 1000) + ' thousand' + ('' if num % 1000 == 0 else ' ' + number_to_words(num % 1000))

    return str(num)  # This function handles up to 999,999; other numbers will be returned as-is

# Convert the cell values in the DataFrame to English words
for col in df_long_table_multiplied.columns:
    df_long_table_multiplied[col] = df_long_table_multiplied[col].apply(lambda x: number_to_words(int(x)))

df_long_table_multiplied.head(10)


Column_0 Column_1  Column_2      Column_3      Column_4     Column_5  \
0     zero     zero      zero          zero          zero         zero   
1     zero      one       two         three          four         five   
2     zero      two      four           six         eight          ten   
3     zero    three       six          nine        twelve      fifteen   
4     zero     four     eight        twelve       sixteen       twenty   
5     zero     five       ten       fifteen        twenty  twenty five   
6     zero      six    twelve      eighteen   twenty four       thirty   
7     zero    seven  fourteen    twenty one  twenty eight  thirty five   
8     zero    eight   sixteen   twenty four    thirty two        forty   
9     zero     nine  eighteen  twenty seven    thirty six   forty five   

      Column_6      Column_7     Column_8      Column_9  
0         zero          zero         zero          zero  
1          six         seven        eight          nine  
2       twelve      fourteen      sixteen      eighteen  
3     eighteen    twenty one  twenty four  twenty seven  
4  twenty four  twenty eight   thirty two    thirty six  
5       thirty   thirty five        forty    forty five  
6   thirty six     forty two  forty eight    fifty four  
7    forty two    forty nine    fifty six   sixty three  
8  forty eight     fifty six   sixty four   seventy two  
9   fifty four   sixty three  seventy two    eighty one

In [16]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [17]:
example_tables = chunk_tables([df_long_table_multiplied, df_long_table_multiplied], 'bert-base-uncased', 512, tokenizer, max_col=3, max_row=10, max_token_per_cell=1)

In [18]:
example_tables = chunk_neighbor_tables([df_long_table_multiplied, df_long_table_multiplied],  'Column_4',2, 'bert-base-uncased', 512, tokenizer)

In [19]:
# for table in example_tables:
#     print(table)

In [20]:
example_tables = chunk_neighbor_tables([df_long_table_multiplied, df_long_table_multiplied],  'Column_4',2, 'bert-base-uncased', 512, tokenizer)

In [21]:
model_name = 'bert-base-uncased'
dataset = TableColumnDataset(example_tables, tokenizer, 512, "[PAD]", model_name)


In [22]:
from torch.utils.data import DataLoader
dataloader = DataLoader(dataset, batch_size=32, shuffle=False)


In [23]:
for batch in dataloader:
    if model_name.startswith("google/tapas"):
        inputs, positions, indices = batch
        print(inputs)
        print(positions)
        print(indices)
        # Further processing for TAPAS model...
    else:
        input_ids, attention_mask, token_positions, positions, indices = batch
        print(input_ids)
        print(attention_mask)
        print(token_positions)
        print(positions)
        print(indices)

tensor([[ 101, 5930, 1035,  ...,    0,    0,    0],
        [ 101, 5930, 1035,  ...,    0,    0,    0],
        [ 101, 5930, 1035,  ...,    0,    0,    0],
        ...,
        [ 101, 5930, 1035,  ...,    0,    0,    0],
        [ 101, 5930, 1035,  ...,    0,    0,    0],
        [ 101, 5930, 1035,  ...,    0,    0,    0]])
tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])
[tensor([0, 0, 0, 0, 0, 0, 0, 0]), tensor([41, 49, 90, 99, 41, 49, 90, 99]), tensor([ 86, 127, 185, 201,  86, 127, 185, 201]), tensor([131, 221, 279, 295, 131, 221, 279, 295]), tensor([177, 310, 367, 384, 177, 310, 367, 384])]
[[tensor([2, 2, 2, 2, 2, 2, 2, 2]), tensor([7, 7, 7, 7, 7, 7, 7, 7])], [tensor([ 0, 25, 50, 75,  0, 25, 50, 75]), tensor([ 25,  50,  75, 100,  25,  50,  75, 100])]]
tensor([0, 0, 0, 0, 1, 1, 1, 1])


In [1]:
from transformers import AutoTokenizer, TapasModel
import pandas as pd

tokenizer = AutoTokenizer.from_pretrained("google/tapas-base")
model = TapasModel.from_pretrained("google/tapas-base")

data = {
    "Actors": ["Brad Pitt", "Leonardo Di Caprio", "George Clooney"],
    "Age": ["56", "45", "59"],
    "Number of movies": ["87", "53", "69"],
}
table = pd.DataFrame.from_dict(data)
queries = [""]

inputs = tokenizer(table=table, queries=queries, padding="max_length", return_tensors="tf")


In [14]:
print(inputs["token_type_ids"][0][:,2])

tf.Tensor(
[0 0 0 0 0 0 0 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0